### ISSUE TITLE
Undefined method `checksum' for Chef::Resource::WindowsPackage with Chef 12.0.0

### ISSUE THREAD

**Issue by dhoer** [agileorbit-cookbooks/java#224]
This seems to be an issue introduced with Chef 12.0.0 and the windows_package resource when provisioning windows machines.  Since chef-client uses the new built in resource windows_package, the checksum attribute might have to be ignored for Chef 12 and greater, and windows section in readme updated to reflect the change https://github.com/agileorbit-cookbooks/java#windows.

For example:
```ruby
chef_windows_package = node['chef_packages']['chef']['version'].split('.')[0].to_i >= 12

windows_package node['java']['windows']['package_name'] do
   source cache_file_path
   checksum node['java']['windows']['checksum'] unless chef_windows_package
   action :install
   installer_type :custom
   options "/s #{additional_options}"
end
```
As of Chef 12, Chef's windows_package is used and it doesn't support checksum so node['java']['windows']['checksum'] is ignored.

Runtime Output:
```
10.168.18.67 [2014-12-05T17:45:15+00:00] INFO: *** Chef 12.0.0 ***
...
10.168.18.67 [2014-12-05T17:45:57+00:00] INFO: Loading cookbooks [sikulix_test@0.1.0, aws@2.5.0, java@1.29.0, windows@1.34.8, chef_handler@1.2.0, sikulix@2.0.0]
...
10.168.18.67 NoMethodError
10.168.18.67 -------------
10.168.18.67 undefined method `checksum' for Chef::Resource::WindowsPackage
10.168.18.67
10.168.18.67 Cookbook Trace:
10.168.18.67 ---------------
10.168.18.67   c:/chef/cache/cookbooks/java/recipes/windows.rb:73:in `block in from_file'
10.168.18.67   c:/chef/cache/cookbooks/java/recipes/windows.rb:71:in `from_file'
10.168.18.67   c:/chef/cache/cookbooks/java/recipes/default.rb:28:in `from_file'
10.168.18.67   c:/chef/cache/cookbooks/sikulix_test/recipes/default.rb:1:in `from_file'
10.168.18.67
10.168.18.67 Relevant File Content:
10.168.18.67 ----------------------
10.168.18.67 c:/chef/cache/cookbooks/java/recipes/windows.rb:
10.168.18.67
10.168.18.67  66:      action :add
10.168.18.67  67:    end
10.168.18.67  68:  end
10.168.18.67  69:
10.168.18.67  70:
10.168.18.67  71:  windows_package node['java']['windows']['package_name'] do
10.168.18.67  72:    source cache_file_path
10.168.18.67  73>>   checksum node['java']['windows']['checksum']
10.168.18.67  74:    action :install
10.168.18.67  75:    installer_type :custom
10.168.18.67  76:    options "/s #{additional_options}"
10.168.18.67  77:  end
```

**Comment by erichelgeson** [comment]
This has been addressed upstream.

**Comment by rammulay** [comment]
I have run into this error - undefined method `checksum' for Chef::Resource::WindowsPackage while installing java on windows server 2012. I am using Chef 12.0.3. Is there a workaround for this issue? I am new to chef so did not quite understand all the comments made since Dec '14!
