### ISSUE TITLE
Fail to extract Oracle Java 7u60 tarball on Amazon Linux

### ISSUE THREAD

**Issue by joni78** [agileorbit-cookbooks/java#225]
I am trying to install Oracle Java 7u60 on an Amazon Linux machine and have a role with the following attributes:

```
    "java": {
      "install_flavor": "oracle",
      "jdk_version": "7",
      "oracle": {
        "accept_oracle_download_terms": true
      },
      "jdk": {
        "7": {
          "x86_64": {
            "url": "http://s3.amazonaws.com/<bucket>/java/jdk-7u60-linux-x64.tar.gz",
            "checksum": "c7232b717573b057dbe828d937ee406b7a75fbc6aba7f1de98a049cbd42c6ae8"
          }
        }
      }
    }
```

However, I get an error saying: FATAL: Failed to extract file jdk-7u60-linux-x64.tar.gz, which continues after cloning the master branch of the cookbook (1.29.0). 

After running chef-client I see in /var/chef/cache the tarball which extracts manually without a problem. After running chef-client I find a tmpdir with the extracted contents of the tarball in /tmp (e.g. /tmp/d20141207-23153-lar4p1).

cheft-client complains about these lines:
```
Cookbook Trace:ESC[0m
---------------ESC[0m
/var/chef/cache/cookbooks/java/providers/ark.rb:154:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/java/providers/ark.rb:130:in `block in class_from_file'ESC[0m
```

So looking at that file these seem to be the relevant lines:

```
149        when /^.*\.(tar.gz|tgz)/
150          cmd = shell_out(
151                             %Q[ tar xvzf "#{Chef::Config[:file_cache_path]}/#{tarball_name}" -C "#{tmpdir}" ]
152                                   ).run_command
153          unless cmd.exitstatus == 0
154            Chef::Application.fatal!("Failed to extract file #{tarball_name}!")
155          end
156        end
```

I don't understand what goes wrong here. Since the tmpdir does contain the as far as I can tell completely extracted tarball, why would it return an exitstatus <>0? 

This is the relevant output of chef-client in debug mode:

```
[2014-12-07T11:10:05+00:00] DEBUG: calculating checksum of /tmp/chef-rest20141207-23153-su98vb to compare with
[2014-12-07T11:10:07+00:00] DEBUG: reading modes from /var/chef/cache/jdk-7u60-linux-x64.tar.gz file
[2014-12-07T11:10:07+00:00] DEBUG: applying mode = 644, uid = 0, gid = 0 to /tmp/chef-rest20141207-23153-su98vb
[2014-12-07T11:10:07+00:00] DEBUG: moving temporary file /tmp/chef-rest20141207-23153-su98vb into place at /var/chef/cache/jdk-7u60-linux-x64.tar.gz
[2014-12-07T11:10:11+00:00] INFO: remote_file[/var/chef/cache/jdk-7u60-linux-x64.tar.gz] updated file contents /var/chef/cache/jdk-7u60-linux-x64.tar.gz
[2014-12-07T11:10:12+00:00] DEBUG: found current_mode == nil, so we are creating a new file, updating mode
[2014-12-07T11:10:12+00:00] DEBUG: found current_mode == nil, so we are creating a new file, updating mode
[2014-12-07T11:10:12+00:00] DEBUG: found target_uid == nil, so no owner was specified on resource, not managing owner
[2014-12-07T11:10:12+00:00] DEBUG: found target_gid == nil, so no group was specified on resource, not managing group
[2014-12-07T11:10:12+00:00] DEBUG: found target_uid == nil, so no owner was specified on resource, not managing owner
[2014-12-07T11:10:12+00:00] DEBUG: found target_gid == nil, so no group was specified on resource, not managing group
[2014-12-07T11:10:12+00:00] DEBUG: found current_mode == nil, so we are creating a new file, updating mode
[2014-12-07T11:10:12+00:00] INFO: remote_file[/var/chef/cache/jdk-7u60-linux-x64.tar.gz] mode changed to 755
[2014-12-07T11:10:12+00:00] DEBUG: selinux utilities can not be found. Skipping selinux permission fixup.
[2014-12-07T11:10:18+00:00] FATAL: Failed to extract file jdk-7u60-linux-x64.tar.gz!
ESC[0m
================================================================================ESC[0m
ESC[31mError executing action `install` on resource 'java_ark[jdk]'ESC[0m
================================================================================ESC[0m

ESC[0m
SystemExitESC[0m
----------ESC[0m
exitESC[0m

ESC[0m
Cookbook Trace:ESC[0m
---------------ESC[0m
/var/chef/cache/cookbooks/java/providers/ark.rb:154:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/java/providers/ark.rb:130:in `block in class_from_file'ESC[0m

ESC[0m
Resource Declaration:ESC[0m
---------------------ESC[0m
# In /var/chef/cache/cookbooks/java/recipes/oracle.rb

 47: java_ark "jdk" do
 48:   url tarball_url
 49:   checksum tarball_checksum
 50:   app_home java_home
 51:   bin_cmds bin_cmds
 52:   alternatives_priority 1062
 53:   action :install
 54: end
 55:
ESC[0m

ESC[0m
Compiled Resource:ESC[0m
------------------ESC[0m
# Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:47:in `from_file'

java_ark("jdk") do
  action [:install]
  supports {:report=>true, :exception=>true}
  retries 0
  retry_delay 2
  cookbook_name "java"
  recipe_name "oracle"
  url "http://s3.amazonaws.com/<bucket>/java/jdk-7u60-linux-x64.tar.gz"
  checksum "c7232b717573b057dbe828d937ee406b7a75fbc6aba7f1de98a049cbd42c6ae8"
  app_home "/usr/lib/jvm/java"
  bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
  alternatives_priority 1062
  default true
end
ESC[0m```

Thanks!

**Comment by mrsipan** [comment]
The recipe is doing a double decompression, one by curl and another by tar. Your s3 object may be misconfigured. Make sure the content-enconding metadata is not set to gzip, otherwise, curl will try to decompress it and since the file is a gzip, it will succeed. Thereafter, tar will try to untar a directory and will fail.

**Comment by erichelgeson** [comment]
@mrsipan I think you're right. My jdk is stored in S3 and I dont have any issue.
