### ISSUE TITLE
hitting a brick wall on trying to install oracle java

### ISSUE THREAD

**Issue by khoan** [agileorbit-cookbooks/java#253]
```bash
$ vagrant provision
Updating Vagrant's berkshelf: '/Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default'
Resolving cookbook dependencies...
Fetching 'issue-elastic' from source at .
Using 7-zip (1.0.2)
Using ark (0.9.0) from git://github.com/burtlo/ark.git (at v0.9.0)
Using build-essential (2.1.3)
Using chef-sugar (2.5.0)
Using chef_handler (1.1.6)
Using elasticsearch (0.3.12) from git://github.com/elasticsearch/cookbook-elasticsearch.git (at 0.3.12)
Using issue-elastic (0.0.1) from source at .
Using java (1.28.0)
Using monit (0.7.5)
Using windows (1.36.6)
Using xml (1.2.13)
Vendoring 7-zip (1.0.2) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/7-zip
Vendoring ark (0.9.0) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/ark
Vendoring build-essential (2.1.3) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/build-essential
Vendoring chef-sugar (2.5.0) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/chef-sugar
Vendoring chef_handler (1.1.6) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/chef_handler
Vendoring elasticsearch (0.3.12) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/elasticsearch
Vendoring issue-elastic (0.0.1) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/issue-elastic
Vendoring java (1.28.0) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/java
Vendoring monit (0.7.5) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/monit
Vendoring windows (1.36.6) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/windows
Vendoring xml (1.2.13) to /Users/khoan/.berkshelf/default/vagrant/berkshelf-20150316-26302-u3od10-default/xml

==> default: Chef 11.10.4 Omnibus package is already installed.
==> default: Running provisioner: chef_solo...
Generating chef JSON and uploading...
==> default: Warning: Chef run list is empty. This may not be what you want.
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-03-16T02:26:12+00:00] INFO: Forking chef instance to converge...
==> default: [2015-03-16T02:26:12+00:00] INFO: *** Chef 11.10.4 ***
==> default: [2015-03-16T02:26:12+00:00] INFO: Chef-client pid: 1880
==> default: [2015-03-16T02:26:12+00:00] INFO: Setting the run_list to ["recipe[issue-elastic]"] from JSON
==> default: [2015-03-16T02:26:12+00:00] INFO: Run List is [recipe[issue-elastic]]
==> default: [2015-03-16T02:26:12+00:00] INFO: Run List expands to [issue-elastic]
==> default: [2015-03-16T02:26:12+00:00] INFO: Starting Chef Run for vagrant-ubuntu-trusty-64
==> default: [2015-03-16T02:26:12+00:00] INFO: Running start handlers
==> default: [2015-03-16T02:26:12+00:00] INFO: Start handlers complete.
==> default: 
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/issue-elastic/recipes/default.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: No resource or method named `java_ark' for `Chef::Recipe "oracle"'
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: 
==> default: ---------------
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/java/recipes/oracle.rb:53:in `from_file'
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/java/recipes/default.rb:28:in `from_file'
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/issue-elastic/recipes/default.rb:8:in `from_file'
==> default: 
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/java/recipes/oracle.rb:
==> default: 
==> default:  46:  
==> default:  47:  if tarball_url =~ /example.com/
==> default:  48:    Chef::Application.fatal!("You must change the download link to your private repository. You can no longer download java directly from http://download.oracle.com without a web broswer")
==> default:  49:  end
==> default:  50:  
==> default:  51:  include_recipe "java::set_java_home"
==> default:  52:  
==> default:  53>> java_ark "jdk" do
==> default:  54:    url tarball_url
==> default:  55:    default node['java']['set_default']
==> default:  56:    checksum tarball_checksum
==> default:  57:    app_home java_home
==> default:  58:    bin_cmds bin_cmds
==> default:  59:    alternatives_priority node['java']['alternatives_priority']
==> default:  60:    retries node['java']['ark_retries']
==> default:  61:    retry_delay node['java']['ark_retry_delay']
==> default:  62:    action :install
==> default: 
==> default: 
==> default: 
==> default: [2015-03-16T02:26:12+00:00] ERROR: Running exception handlers
==> default: [2015-03-16T02:26:12+00:00] ERROR: Exception handlers complete
==> default: [2015-03-16T02:26:12+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-03-16T02:26:12+00:00] ERROR: No resource or method named `java_ark' for `Chef::Recipe "oracle"'
==> default: [2015-03-16T02:26:12+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by erichelgeson** [comment]
Without showing me how you are trying to use the cookbook I cant help (what attributes you have set, how you're using it, etc)

There was a time where oracle was changing download "protections" frequently. It is always recommended as well that you mirror your copy of the jdk in case that were to happen in the future. 

Please also use the latest version (1.31.0)

**Comment by khoan** [comment]
I'm using berkshelf and testing on vagrant. Thanks for the quick response.

```
$ cat Vagrantfile
...
    custom_json_file = File.expand_path("../custom.json", __FILE__)
    run_list = {
      "run_list" => [
        "recipe[issue-elastic]"
      ]
    }
    chef_json = JSON.parse(IO.read(custom_json_file))
    chef.json = chef_json.merge(run_list)
...

$ cat custom.json 
{
  "java": {
    "jdk_version": "7",
    "install_flavor" : "oracle",
    "oracle" : { "accept_oracle_download_terms" : "true" },
    "accept_license_agreement" : "true",
    "arch" : "x86_64",
    "jdk" : {
      "7" : {
        "x86_64" : {
          "url" : "https://s3.amazonaws.com/path/to/jdk-7u75-linux-x64.tar.gz",
          "checksum" : "cef77f13bac96eb472c02fac0da6cbcf"
        }
      }
    }
  }
}
$ berks 
Resolving cookbook dependencies...
Fetching 'issue-elastic' from source at .
Fetching cookbook index from https://supermarket.getchef.com...
Using 7-zip (1.0.2)
Using build-essential (2.1.3)
Using ark (0.9.0) from git://github.com/burtlo/ark.git (at v0.9.0)
Using chef-sugar (2.5.0)
Using chef_handler (1.1.6)
Using issue-elastic (0.0.1) from source at .
Using elasticsearch (0.3.12) from git://github.com/elasticsearch/cookbook-elasticsearch.git (at 0.3.12)
Using java (1.31.0)
Using windows (1.36.6)
Using monit (0.7.5)
Using xml (1.2.13)

$ cat recipes/default.rb 
include_recipe 'java'
```

**Comment by khoan** [comment]
I've created a simple repo: https://github.com/khoan/test-opsworks

**Comment by khoan** [comment]
I didn't include dependency on java in metadata.rb

```
depends 'java'
```
