### ISSUE TITLE
Cookbook fails on SmartOS machines

### ISSUE THREAD

**Issue by hulu1522** [agileorbit-cookbooks/java#255]
I am running this on Joyent's SmartOS machines and keep getting this error:

```
       Synchronizing Cookbooks:
         - java
       Compiling Cookbooks...
       Converging 4 resources
       Recipe: java::set_java_home
         * ruby_block[set-env-java-home] action run
           - execute the ruby block set-env-java-home
         * directory[/etc/profile.d] action create
           - create new directory /etc/profile.d
           - change mode from '' to '0755'
         * file[/etc/profile.d/jdk.sh] action create
           - create new file /etc/profile.d/jdk.sh
           - update content in file /etc/profile.d/jdk.sh from none to 61b1f8
           --- /etc/profile.d/jdk.sh   2015-03-18 22:51:26.175891846 +0000
           +++ /etc/profile.d/.jdk.sh20150318-76506-9ztpa2     2015-03-18 22:51:26.175673897 +0000
           @@ -1 +1,2 @@
           +export JAVA_HOME=/opt/local/java/sun6
           - change mode from '' to '0755'
       Recipe: java::oracle
         * java_ark[jdk] action install
           - create dir /opt/local/java and change owner to root:root
           * smartos_package[curl] action install (up to date)
           - download oracle tarball straight from the server
           - extract compressed data into Chef file cache path and

           - Symlink /opt/local/java/jdk1.7.0_75 to /opt/local/java/sun6
         * smartos_package[curl] action nothing (skipped due to action :nothing)
         * java_alternatives[set-java-alternatives] action set

           ================================================================================
           Error executing action `set` on resource 'java_alternatives[set-java-alternatives]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - update-alternatives

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/java/providers/alternatives.rb:42:in `block (3 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/java/providers/alternatives.rb:39:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/java/providers/alternatives.rb:24:in `each'
       /tmp/kitchen/cache/cookbooks/java/providers/alternatives.rb:24:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/java/providers/ark.rb

       219:   java_alternatives 'set-java-alternatives' do
       220:     java_location app_home
       221:     bin_cmds new_resource.bin_cmds
       222:     priority new_resource.alternatives_priority
       223:     default new_resource.default
       224:     action :set
           225:   end
           226: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/java/providers/ark.rb:219:in `block in class_from_file'

       java_alternatives("set-java-alternatives") do
         action [:set]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         declared_type :java_alternatives
         cookbook_name "java"
             java_location "/opt/local/java/sun6"
             bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
         priority 1062
         default true
           end

       [2015-03-18T22:51:38+00:00] ERROR: Converge failed with error message java_alternatives[set-java-alternatives] (/tmp/kitchen/cache/cookbooks/java/providers/ark.rb line 219) had an error: Errno::ENOENT: No such file or directory - update-alternatives

       Running handlers:
       [2015-03-18T22:51:38+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-18T22:51:38+00:00] ERROR: Exception handlers complete
       [2015-03-18T22:51:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 4 resources updated in 14.906527449 seconds
       [2015-03-18T22:51:38+00:00] ERROR: Found 1 errors, they are stored in the backtrace
       [2015-03-18T22:51:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-smartos-postgresql>.
>>>>>> Please see .kitchen/logs/default-smartos-postgresql.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

If you need any more information let me know.  Thanks.

**Comment by MrWong99** [comment]
This is saying your shell couldn't find a location for a command named "update-alternatives".

Possible reasons for this:

1) The path where the command exists is not in your PATH variable.

2) The command is not on your system. (which it usually should be)

3) The command is on your system but doesn't have execute bit set so isn't recongized as an executable.

To find where the command is:

find / -name update-alternatives

The above should print out the full directory for this command (e.g. /usr/local/bin/update-alternatives).
You would then type "echo $PATH" and see if that path (e.g. /usr/local/bin) appears in the output separated by colons from other paths in the variable. If not you can append it to the PATH variable by typing "PATH=$PATH:/usr/local/bin" (/usr/local/bin is ONLY an example - you'd substitute whatever path alternatives was found in here).

**Comment by erichelgeson** [comment]
It looks like this has since been addressed 
https://github.com/agileorbit-cookbooks/java/blob/99acaf85d906764fafdb7e3d46e4ecb2ff1793d0/spec/openjdk_spec.rb#L25-L28

https://github.com/agileorbit-cookbooks/java/blob/99acaf85d906764fafdb7e3d46e4ecb2ff1793d0/spec/openjdk_spec.rb#L49-L55
