### ISSUE TITLE
Amazon Linux Checksum failing S3 hosted JDK Chef::Exceptions::ChecksumMismatch

### ISSUE THREAD

**Issue by lantrix** [agileorbit-cookbooks/java#256]
I have the JDK 7 file on an S3 bucket; and have the recipe attributes over-ridden by the role used to run the Java recipe:

```
{
    "name": "java-appserver",
    "default_attributes": {},
    "override_attributes": {
        "java": {
            "jdk": {
                "7": {
                    "x86_64": {
                        "url": "https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz"
                    }
                }
            },
            "oracle": {
                "accept_oracle_download_terms": true
            }
        }
    },
    "json_class": "Chef::Role",
    "chef_type": "role",
    "run_list": [
        "recipe[java]" 
    ]
}
```

However; I'm unable to get this working as the gz never downloads to `/var/chef/cache/jdk-7u75-linux-x64.tar.gz`. When I do a client run with debug; chef downloads the file to a /tmp location but it never ends up in the chef cache. Therefore the checksum fails.

```
[2015-03-26T00:07:10+00:00] DEBUG: downloading tarball from an unofficial repository

    * remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] action create_if_missing[2015-03-26T00:07:10+00:00] INFO: Processing remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] action create_if_missing (/var/chef/cache/cookbooks/java/providers/ark.rb line 128)
[2015-03-26T00:07:10+00:00] DEBUG: remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] checking for changes
[2015-03-26T00:07:10+00:00] DEBUG: turning gzip compression off due to filename ending in gz
[2015-03-26T00:07:10+00:00] DEBUG: Cache control headers: {}
[2015-03-26T00:07:10+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
[2015-03-26T00:07:10+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
[2015-03-26T00:07:10+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
[2015-03-26T00:07:10+00:00] DEBUG: Initiating GET to https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz
[2015-03-26T00:07:10+00:00] DEBUG: ---- HTTP Request Header Data: ----
[2015-03-26T00:07:10+00:00] DEBUG: ---- End HTTP Request Header Data ----
[2015-03-26T00:07:10+00:00] DEBUG: ---- HTTP Status and Header Data: ----
[2015-03-26T00:07:10+00:00] DEBUG: HTTP 1.1 200 OK
[2015-03-26T00:07:10+00:00] DEBUG: x-amz-id-2: DZ1HkwFDKoQP0RZpDgPiCcImRPySzMTU+7M2dDrr/we9osc3FQhxOqyal03069Jv
[2015-03-26T00:07:10+00:00] DEBUG: x-amz-request-id: 0A7F8F1A32132E05
[2015-03-26T00:07:10+00:00] DEBUG: date: Thu, 26 Mar 2015 00:07:11 GMT
[2015-03-26T00:07:10+00:00] DEBUG: last-modified: Wed, 25 Mar 2015 23:39:49 GMT
[2015-03-26T00:07:10+00:00] DEBUG: etag: "6259b6b6a732e590d9c20ced0a340638-3"
[2015-03-26T00:07:10+00:00] DEBUG: accept-ranges: bytes
[2015-03-26T00:07:10+00:00] DEBUG: content-type: application/x-gzip
[2015-03-26T00:07:10+00:00] DEBUG: content-length: 142245547
[2015-03-26T00:07:10+00:00] DEBUG: server: AmazonS3
[2015-03-26T00:07:10+00:00] DEBUG: connection: close
[2015-03-26T00:07:10+00:00] DEBUG: ---- End HTTP Status/Header Data ----
[2015-03-26T00:07:10+00:00] DEBUG: Streaming download from https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz to tempfile /tmp/chef-rest20150326-9426-12ck2b0
[2015-03-26T00:07:10+00:00] DEBUG: disable_gzip is set.             Not using              and initializing noop stream deflator.
[2015-03-26T00:07:10+00:00] DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::ValidateContentLength::ContentLengthCounter#handle_chunk
[2015-03-26T00:07:10+00:00] DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::Decompressor::NoopInflater#handle_chunk
<snip>
[2015-03-26T00:07:20+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
[2015-03-26T00:07:20+00:00] DEBUG: Content-Length validated correctly.
[2015-03-26T00:07:20+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
[2015-03-26T00:07:20+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
      ================================================================================
      Error executing action `create_if_missing` on resource 'remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz]'
      ================================================================================
      
      Chef::Exceptions::ChecksumMismatch
      ----------------------------------
      Checksum on resource (6f1f81) does not match checksum on content (460959)
```

I thought this may be like other Amazon Linux issues with S3 having the `Content-Encoding` set incorrectly https://github.com/agileorbit-cookbooks/java/issues/225 ; but it seems not. In the case of Issue 225 the tarball is put in the chef cache; but there are issues with the gzip handling on S3.

Curl for me doesn't show a gzip `Content-Encoding` header:

```
[root@ip-172-21-1-4 tmp]# curl --header 'Accept: application/x-gzip' -I -vvv https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz
*   Trying 54.231.252.9...
* Connected to s3-ap-southeast-2.amazonaws.com (54.231.252.9) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* 	subject: CN=*.s3-ap-southeast-2.amazonaws.com,O="Amazon.com, Inc.",L=Seattle,ST=Washington,C=US
* 	start date: Oct 02 00:00:00 2014 GMT
* 	expire date: Sep 12 23:59:59 2015 GMT
* 	common name: *.s3-ap-southeast-2.amazonaws.com
* 	issuer: CN=VeriSign Class 3 Secure Server CA - G3,OU=Terms of use at https://www.verisign.com/rpa (c)10,OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
> HEAD /seek-simian-army/build/jdk-7u75-linux-x64.tar.gz HTTP/1.1
> User-Agent: curl/7.40.0
> Host: s3-ap-southeast-2.amazonaws.com
> Accept: application/x-gzip
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< x-amz-id-2: v8BwQQpssmKP821UNXTqELlNMImAtkBZ6kbeIFjSMyiGyIHCy+3rurVlklhHSanj
x-amz-id-2: v8BwQQpssmKP821UNXTqELlNMImAtkBZ6kbeIFjSMyiGyIHCy+3rurVlklhHSanj
< x-amz-request-id: A4DDF21BB45BB05B
x-amz-request-id: A4DDF21BB45BB05B
< Date: Thu, 26 Mar 2015 00:12:52 GMT
Date: Thu, 26 Mar 2015 00:12:52 GMT
< Last-Modified: Wed, 25 Mar 2015 23:39:49 GMT
Last-Modified: Wed, 25 Mar 2015 23:39:49 GMT
< ETag: "6259b6b6a732e590d9c20ced0a340638-3"
ETag: "6259b6b6a732e590d9c20ced0a340638-3"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Type: application/x-gzip
Content-Type: application/x-gzip
< Content-Length: 142245547
Content-Length: 142245547
< Server: AmazonS3
Server: AmazonS3

< 
* Connection #0 to host s3-ap-southeast-2.amazonaws.com left intact
```

Full failure:

```
Recipe: java::oracle
  * java_ark[jdk] action install
    * remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] action create_if_missing
      
      ================================================================================
      Error executing action `create_if_missing` on resource 'remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz]'
      ================================================================================
      
      Chef::Exceptions::ChecksumMismatch
      ----------------------------------
      Checksum on resource (6f1f81) does not match checksum on content (460959)
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/java/providers/ark.rb:137:in `block in class_from_file'
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/java/providers/ark.rb
      
      128:       r = remote_file "#{Chef::Config[:file_cache_path]}/#{tarball_name}" do
      129:         source new_resource.url
      130:         checksum new_resource.checksum
      131:         retries new_resource.retries
      132:         retry_delay new_resource.retry_delay
      133:         mode 0755
      134:         action :nothing
      135:       end
      136:       #no converge by on run_action remote_file takes care of it.
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/java/providers/ark.rb:128:in `block in class_from_file'
      
      remote_file("/var/chef/cache/jdk-7u75-linux-x64.tar.gz") do
        provider Chef::Provider::RemoteFile
        action [:nothing]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/var/chef/cache/jdk-7u75-linux-x64.tar.gz"
        backup 5
        atomic_update true
        source ["https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz"]
        use_etag true
        use_last_modified true
        declared_type :remote_file
        cookbook_name "java"
        checksum "6f1f81030a34f7a9c987f8b68a24d139"
        mode 493
      end
      
    
    ================================================================================
    Error executing action `install` on resource 'java_ark[jdk]'
    ================================================================================
    
    Chef::Exceptions::ChecksumMismatch
    ----------------------------------
    remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] (/var/chef/cache/cookbooks/java/providers/ark.rb line 128) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (6f1f81) does not match checksum on content (460959)
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/java/providers/ark.rb:137:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/java/recipes/oracle.rb
    
     53: java_ark "jdk" do
     54:   url tarball_url
     55:   default node['java']['set_default']
     56:   checksum tarball_checksum
     57:   app_home java_home
     58:   bin_cmds bin_cmds
     59:   alternatives_priority node['java']['alternatives_priority']
     60:   retries node['java']['ark_retries']
     61:   retry_delay node['java']['ark_retry_delay']
     62:   connect_timeout node['java']['ark_timeout']
     63:   action :install
     64: end
     65: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:53:in `from_file'
    
    java_ark("jdk") do
      action [:install]
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :java_ark
      cookbook_name "java"
      recipe_name "oracle"
      url "https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz"
      default true
      checksum "6f1f81030a34f7a9c987f8b68a24d139"
      app_home "/usr/lib/jvm/java"
      bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
      alternatives_priority 1062
      connect_timeout 600
      owner "root"
    end
```

My workaround for now is to manually use curl to download the gz into `/var/chef/cache/jdk-7u75-linux-x64.tar.gz`:

```
[root@ip-172-21-1-4 tmp]# curl https://s3-ap-southeast-2.amazonaws.com/seek-simian-army/build/jdk-7u75-linux-x64.tar.gz -o /var/chef/cache/jdk-7u75-linux-x64.tar.gz
[root@ip-172-21-1-4 tmp]# ls -l /var/chef/cache/jdk-7u75-linux-x64.tar.gz
-rw-r--r-- 1 root root 142245547 Mar 26 00:15 /var/chef/cache/jdk-7u75-linux-x64.tar.gz
```

After that the recipe works:
```
Recipe: java::oracle
  * java_ark[jdk] action install
    * remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] action create_if_missing (up to date)
    - extract compressed data into Chef file cache path and
                        move extracted data to /usr/lib/jvm/jdk1.7.0_75
    - Symlink /usr/lib/jvm/jdk1.7.0_75 to /usr/lib/jvm/java
  * remote_file[/var/chef/cache/jdk-7u75-linux-x64.tar.gz] action nothing (skipped due to action :nothing)
```

**Comment by dzabel** [comment]
Yesterday i stumbled into the same issue.
My workaround was to use sha256sum as checksum - amazon use this per default.

Have a look at your error:

```
Checksum on resource (6f1f81) does not match checksum on content (460959)
```

and the output from

```
sha256sum jdk-7u75-linux-x64.tar.gz
460959219b534dc23e34d77abc306e180b364069b9fc2b2265d964fa2c281610  jdk-7u75-linux-x64.tar.gz

```

**Comment by lantrix** [comment]
I was wondering where this sum was coming from :) I'll try it out.

**Comment by kamal079** [comment]
Thanks dzabel. The documentation says ['checksum'] can be either sha256 or checksum. I faced the same issue , however adding md5sum value to 'checksum'  attribute solved the issue.

I used ```md5sum```  to generate the MD5 value.
