### ISSUE TITLE
Download Java package failed

### ISSUE THREAD

**Issue by WeiBanjo** [agileorbit-cookbooks/java#302]
We are seeing issue to download Java package and using this commit `28dab32aefb48358d9f19dadcbb0c44e4346e042`. 

Please see full trace as below. Let me know if anyone have a fix for it. Thanks

```    ================================================================================
    Error executing action `install` on resource 'java_ark[jdk]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '18'
    ---- Begin output of  curl --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz -o /var/chef/cache/jdk-8u60-linux-x64.tar.gz --connect-timeout 600  ----
    STDOUT:
    STDERR: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0   288    0     0    560      0 --:--:-- --:--:-- --:--:--   560
 11  172M   11 20.0M    0     0  13.3M      0  0:00:12  0:00:01  0:00:11 20.5M
    curl: (18) transfer closed with 160267123 bytes remaining to read
    ---- End output of  curl --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz -o /var/chef/cache/jdk-8u60-linux-x64.tar.gz --connect-timeout 600  ----
    Ran  curl --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz -o /var/chef/cache/jdk-8u60-linux-x64.tar.gz --connect-timeout 600  returned 18

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/java/providers/ark.rb:80:in `block in download_direct_from_oracle'
    /var/chef/cache/cookbooks/java/providers/ark.rb:78:in `download_direct_from_oracle'
    /var/chef/cache/cookbooks/java/providers/ark.rb:125:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/java/recipes/oracle.rb

     55: java_ark "jdk" do
     56:   url tarball_url
     57:   default node['java']['set_default']
     58:   checksum tarball_checksum
     59:   app_home java_home
     60:   bin_cmds bin_cmds
     61:   alternatives_priority node['java']['alternatives_priority']
     62:   retries node['java']['ark_retries']
     63:   retry_delay node['java']['ark_retry_delay']
     64:   connect_timeout node['java']['ark_timeout']
     65:   use_alt_suffix node['java']['use_alt_suffix']
     66:   reset_alternatives node['java']['reset_alternatives']
     67:   download_timeout node['java']['ark_download_timeout']
     68:   action :install
     69: end
     70:
     71: if node['java']['set_default'] and platform_family?('debian')
     72:   include_recipe 'java::default_java_symlink'
     73: end
     74:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:55:in `from_file'

    java_ark("jdk") do
      action [:install]
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :java_ark
      cookbook_name "java"
      recipe_name "oracle"
      url "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz"
      default true
      checksum "b8ca513d4f439782c019cb78cd7fd101"
      app_home "/usr/lib/jvm/java"
      bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jdeps", "jhat", "jinfo", "jjs", "jmap", "jmc", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
      alternatives_priority 1062
      connect_timeout 600
      use_alt_suffix true
      reset_alternatives true
      download_timeout 600
      owner "root"
    end

```

**Comment by erichelgeson** [comment]
This looks like your network connection was interrupted mid download. Can you try caching the archive close to your app server instead of directly downloading from Oracle?

**Comment by WeiBanjo** [comment]
OK. Thanks
