### ISSUE TITLE
Package-Problems on Mac OS X

### ISSUE THREAD

**Issue by Elias-from-Testfabrik** [agileorbit-cookbooks/java#342]
Your statement _package "tar"_ in oracle.rb causes issues on Mac OS X when using Homebrew. While being installed as _tar_ as normally, the formula name required by brew is actually is 'gnu-tar'. Which of course leads to brew complaining that the package does not exist, consequently we get an exception and java will never be installed.

Relevant stacktrace and output:
```
Processing homebrew_package[tar] action install (java::oracle line 53)
Error executing action `install` on resource 'homebrew_package[tar]'
Mixlib::ShellOut::ShellCommandFailed

Cookbook Trace:

/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:95:in `get_response_from_command'
/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:70:in `brew'
/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:86:in `package_info'
/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:74:in `current_installed_version'
/var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:44:in `load_current_resource'

Resource Declaration:

In /var/chef/cache/cookbooks/java/recipes/oracle.rb

53: package "tar"
54: 

Compiled Resource:
Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:53:in `from_file'

homebrew_package("tar") do
  action :install
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  package_name "tar"
  timeout 900
  declared_type :package
  cookbook_name "java"
  recipe_name "oracle"
end
ERROR: homebrew_package[tar] (java::oracle line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
Error: No available formula with the name "tar"
```

**Comment by Elias-from-Testfabrik** [comment]
I think your fix is incomplete but I cannot reopen the issue, hence I commented the commit.
