### ISSUE TITLE
Oracle JDK Installation fails on windows server running on Azure

### ISSUE THREAD

**Issue by sernapallyanurag** [agileorbit-cookbooks/java#345]
```
[2016-05-06T10:57:39+00:00] FATAL: No download url set for java installer.
===============================================================================
Recipe Compile Error in c:/chef/cache/cookbooks/java/recipes/default.rb
===============================================================================

URI::InvalidURIError
--------------------
bad URI(is not URI?):

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/java/recipes/windows.rb:29:in `from_file'
  c:/chef/cache/cookbooks/java/recipes/default.rb:22:in `from_file'

Relevant File Content:
----------------------
c:/chef/cache/cookbooks/java/recipes/windows.rb:
 22:
 23:  Chef::Log.fatal('No download url set for java installer.') unless node['java'] && node['java']['windows'] && node[
'java']['windows']['url']
 24:
 25:  pkg_checksum = node['java']['windows']['checksum']
 26:  aws_access_key_id = node['java']['windows']['aws_access_key_id']
 27:  aws_secret_access_key = node['java']['windows']['aws_secret_access_key']
 28:
 29>> uri = ::URI.parse(node['java']['windows']['url'])
 30:  cache_file_path = File.join(Chef::Config[:file_cache_path], File.basename(::URI.unescape(uri.path)))
 31:
 32:  if aws_access_key_id && aws_secret_access_key
 33:    include_recipe 'aws::default' # install right_aws gem for aws_s3_file
 34:
 35:    aws_s3_file cache_file_path do
 36:      aws_access_key_id aws_access_key_id
 37:      aws_secret_access_key aws_secret_access_key
 38:      checksum pkg_checksum if pkg_checksum

Platform:
---------
x64-mingw32

←[0m
Running handlers:
[2016-05-06T10:57:39+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-05-06T10:57:39+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 32 seconds
[2016-05-06T10:57:40+00:00] INFO: Sending resource update report (run-id: d67ef516-4bf3-4e19-ac9a-3c3e636f9d0b)
[2016-05-06T10:57:41+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2016-05-06T10:57:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-05-06T10:57:41+00:00] FATAL: URI::InvalidURIError: bad URI(is not URI?):
```

**Comment by erichelgeson** [comment]
Have you tried what the error message says to do?

**Comment by sernapallyanurag** [comment]
Thanks for the response.
I don't have aws subscription so i could not  set an url to download installer. But I required Oracle java so I used Java_se cookbook.

**Comment by erichelgeson** [comment]
AWS is not a requirement for this cookbook - you can set the URL to any location your server has access to.
