### ISSUE TITLE
Deprecated features used!

### ISSUE THREAD

**Issue by tiago-cruz-movile** [agileorbit-cookbooks/java#399]
- version           '1.47.0'

```
Deprecated features used!
  proxy nil currently does not overwrite the value of proxy. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/cache/chef/cookbooks/java/recipes/oracle.rb:72:in `block in from_file'
```

**Comment by grv87** [comment]
I have the following warnings:
```
  Property `retries` of resource `java_ark` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/java/resources/ark.rb:46:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
  Property `retry_delay` of resource `java_ark` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/java/resources/ark.rb:47:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
```

**Comment by e100** [comment]
The properties retries and retry_delay are now built in properties for all resources.
https://docs.chef.io/resource_common.html

**Comment by kylegoch** [comment]
Looks like this is fixed in #403, however the newer version with that merge hasnt been released yet.
