### ISSUE TITLE
homebrew cookbook causes failures when running as root

### ISSUE THREAD

**Issue by monkey1016** [agileorbit-cookbooks/java#456]
### Cookbook version
1.50.0

### Chef-client version
12.17.44

### Platform Details
RHEL 6.9

### Scenario:
N/A

### Steps to Reproduce:
Use `homebrew` version `5.0.1`

### Expected Result:
Run `java::default`

### Actual Result:
```
Recipe Compile Error in /var/chef/cache/cookbooks/homebrew/resources/cask.rb
                                          ================================================================================

                                          Chef::Exceptions::User
                                          ----------------------
                                          Homebrew owner is 'root' which is not supported. To set an explicit owner, please set node['homebrew']['owner'].

                                          Cookbook Trace:
                                          ---------------
                                            /var/chef/cache/cookbooks/homebrew/libraries/helpers.rb:50:in `calculate_owner'
                                            /var/chef/cache/cookbooks/homebrew/libraries/helpers.rb:39:in `rescue in owner'
                                            /var/chef/cache/cookbooks/homebrew/libraries/helpers.rb:35:in `owner'
                                            /var/chef/cache/cookbooks/homebrew/resources/cask.rb:25:in `class_from_file'

                                          Relevant File Content:
                                          ----------------------
                                          /var/chef/cache/cookbooks/homebrew/libraries/helpers.rb:

                                           43:    end
                                           44:
                                           45:    private
                                           46:
                                           47:    def calculate_owner
                                           48:      owner = homebrew_owner_attr || sudo_user || current_user
                                           49:      if owner == 'root'
                                           50>>       raise Chef::Exceptions::User,
                                           51:             "Homebrew owner is 'root' which is not supported. " \
                                           52:             "To set an explicit owner, please set node['homebrew']['owner']."
                                           53:      end
                                           54:      owner
                                           55:    end
                                           56:
                                           57:    def homebrew_owner_attr
                                           58:      Chef.node['homebrew']['owner']
                                           59:    end

                                          Platform:
                                          ---------
                                          x86_64-linux
```

**Comment by monkey1016** [comment]
Downgrading to the homebrew version to `4.3.0` works.

**Comment by tas50** [comment]
Homebrew 5.0.2 fixes this issue.

**Comment by monkey1016** [comment]
Closing the issue since a new version of the Homebrew cookbook resolves the issue.
